server:
  port: 8072

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

info:
  app:
    name: GearHead Online SHop
    description: This project is about an online shop with microservices
    version: 1.0.0
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true
