spring:
  cloud:
    compatibility-verifier:
      enabled : false
  management:
    endpoints:
      web:
        exposure:
          include: "*"
  datasource:
    url: jdbc:postgresql://localhost:5432/gearhead_product
    username: account
    password: account123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs:
    path: /api-docs
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
# acturator info endpoint
info:
  app:
    name: GearHead Online SHop
    description: This project is about online shop with micorservice
    version: 1.0.0
management:
  info:
    env: 
      enabled: true
